#!/usr/bin/env bash
# Script to display subdomain DNS A records

# Function to get A record for a subdomain
get_record() {
  local full_domain="${1}.${2}"
  local ip=$(dig +short "$full_domain" | head -n1)
  if [[ -n "$ip" ]]; then
    echo "The subdomain $1 is a A record and points to $ip"
  fi
}

domain=$1
sub=$2

if [[ -z "$domain" ]]; then
  echo "Domain is required"
  exit 1
fi

if [[ -z "$sub" ]]; then
  for s in www lb-01 web-01 web-02
  do
    get_record "$s" "$domain"
  done
else
  get_record "$sub" "$domain"
fi
