#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
# shellcheck disable=SC2154

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

# Create basic index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Add custom header to nginx configuration
sed -i "/server_name _;/a\\        add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Test nginx configuration and restart
nginx -t
service nginx restart