#!/usr/bin/env bash
# Script to install and configure HAProxy on a new Ubuntu server

# Install haproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to start on boot
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5s
    timeout client  50s
    timeout server  50s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 18.206.224.177:80 check
    server web-02 3.83.102.47:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy